### PR TITLE
Split ExtendedSQLiteOpenHelper into two classes

### LINKED ISSUE #57: getDatabaseHelper(Context context) has incorrect declaration.
SQLiteContentProviderImpl has the following implementation of getDatabaseHelper():

```
@Override
protected SQLiteOpenHelper getDatabaseHelper(Context context) {
    try {
        return new ExtendedSQLiteOpenHelper(context, getCursorFactory());
    } catch (IOException e) {
        Log.Provider.e(e);
        throw new IllegalStateException(e.getMessage());
    }
}
```

It looks like I can redefine this function and return my own SQLiteOpenHelper. But it doesn't work: somewhere in the lib will be casting back to ExtendedSQLiteOpenHelper:

Caused by: java.lang.ClassCastException: ru.jollydroid.app.Db cannot be cast to novoda.lib.sqliteprovider.sqlite.ExtendedSQLiteOpenHelper
at novoda.lib.sqliteprovider.provider.SQLiteContentProviderImpl.onCreate(SQLiteContentProviderImpl.java:43)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)

I think you need to split ExtendedSQLiteOpenHelper to two classes. One with common helper functions like getColumns() and getTables, and one with implementation of your helper.

### PR DESCRIPTION
**Pull request by friedger**
This PR splits ExtendedSQLiteOpenHelper into two classes: MigratingSQLiteOpenHelper and SQLiteDatabaseMetaInfo. This separates the concerns and allows to provide customized open helpers.

While splitting the class the deprecated APIs have not been moved, but removed where possible.

Tests have not been added or separated to show that all tests still pass.

This fixes #57

### CODE REVIEW

**Comment by stefanhoth** [comment]
Can one of the admins review this PR?

**Comment by friedger** [comment]
any comments?

**Comment by rock3r** [comment]
hal test this please

File: core/src/main/java/novoda/lib/sqliteprovider/provider/action/InsertHelper.java [hunk 1]
```diff
@@ -22,16 +24,18 @@
  */
 public class InsertHelper {
 
-    private final ExtendedSQLiteOpenHelper dbHelper;
+    private final SQLiteOpenHelper dbHelper;
+    private final SQLiteDatabaseMetaInfo metaInfo;
 
-    public InsertHelper(ExtendedSQLiteOpenHelper helper) {
-        this.dbHelper = helper;
+    public InsertHelper(SQLiteOpenHelper databaseHelper, SQLiteDatabaseMetaInfo metaInfo) {
```
Comment (rock3r) [inline core/src/main/java/novoda/lib/sqliteprovider/provider/action/InsertHelper.java]: These changes require a major release ⚠️  -- it's fine since #69 and #70 will require one anyway

File: core/src/main/java/novoda/lib/sqliteprovider/sqlite/SQLiteDatabaseMetaInfo.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+import android.database.sqlite.SQLiteOpenHelper;
+
+import java.util.HashMap;
+import java.util.List;
+import java.util.Map;
+
+import novoda.lib.sqliteprovider.util.Constraint;
+import novoda.lib.sqliteprovider.util.DBUtils;
+
+/**
```
Comment (rock3r) [inline core/src/main/java/novoda/lib/sqliteprovider/sqlite/SQLiteDatabaseMetaInfo.java]: Can you please take this out @friedger?

File: core/src/main/java/novoda/lib/sqliteprovider/sqlite/SQLiteDatabaseMetaInfo.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+    private final Map<String, List<Constraint>> constraints = new HashMap<String, List<Constraint>>();
+    private final SQLiteOpenHelper helper;
+
+    public SQLiteDatabaseMetaInfo(SQLiteOpenHelper helper) {
+        this.helper = helper;
+    }
+
+    @Override
+    public Map<String, SQLiteType> getColumns(String table) {
+        return DBUtils.getFields(helper.getReadableDatabase(), table);
```
Comment (rock3r) [inline core/src/main/java/novoda/lib/sqliteprovider/sqlite/SQLiteDatabaseMetaInfo.java]: Might clash with the work in #69 but I suppose @eduardb can adjust accordingly

**Review by rock3r — COMMENTED** [review]
Seems OK to me, once the stray Javadoc is taken out it's good to go

File: core/src/main/java/novoda/lib/sqliteprovider/sqlite/SQLiteDatabaseMetaInfo.java (hunk 3 above)
Comment (eduardb) [inline core/src/main/java/novoda/lib/sqliteprovider/sqlite/SQLiteDatabaseMetaInfo.java]: Yes, we can get this PR merged first. It should go smoother 😄

**Review by eduardb — APPROVED** [review]
Besides what @rock3r already said, it looks great to me 👍

**Review by rock3r — CHANGES_REQUESTED** [review]
Need to remove the autogenerated "author" javadoc

**Comment by rock3r** [comment]
Sorry I had forgotten to click "request changes" before :D

**Comment by friedger** [comment]
Comments addressed :-)

**Review by rock3r — APPROVED** [review]

**Comment by rock3r** [comment]
hal test this please

**Comment by rock3r** [comment]
Thanks @friedger

**Comment by rock3r** [comment]
:shipit:
