### PR TITLE
Fix update behaviour in content provider implementation

### LINKED ISSUE #22: SQLiteContentProviderImpl.java return value incorrect
An update method returns number of rows affected, not a rowID. Code should read:
```
int count = getWritableDatabase().update(UriUtils.getItemDirID(uri), insertValues, selection, selectionArgs);
```
......
```
return count;
```
The notifyUriChange() call is notifying some completely unrelated observer.
``` 
@Override
    protected int updateInTransaction(Uri uri, ContentValues values, String selection, String[] selectionArgs) {
        ContentValues insertValues = (values != null) ? new ContentValues(values) : new ContentValues();

        int rowId = getWritableDatabase().update(UriUtils.getItemDirID(uri), insertValues, selection, selectionArgs);

        if (rowId > 0) {
            Uri insertUri = ContentUris.withAppendedId(uri, rowId);
            notifyUriChange(insertUri);
            return rowId;
        }
        throw new SQLException("Failed to update row into " + uri + " because it does not exists.");
    }
```

### PR DESCRIPTION
**Pull request by eduardb**
#### Problem
The content provider implementation was throwing a `SQLException` when trying to run an update and there were no rows matching the selection arguments. This is breaking the sqlite contract, as it should return the number of affected rows (see [Android documentation](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#update(java.lang.String, android.content.ContentValues, java.lang.String, java.lang.String[]))). The underlying `SQLiteDatabase` could throw a `SQLiteConstraintException` in case of a constraint violation, but that's none of the provider's business.

#### Solution
Remove the thrown exception, and just return the number of affected rows. Also, notify the correct `Uri` if something has been updated, as previously a wrong `Uri` was notified for the change, because there was the assumption that `SQLiteDatabase.update()` returns an ID, not the number of affected rows. 😛 

#### Tests
Yes, added test in `ContentProviderTest` that is showcasing the correct behaviour.

Also, this fixes #22 :)

Paired with @lgvalle

### CODE REVIEW

**Comment by frapontillo** [comment]
On master? If this breaks the previous contract we should aim for a new major.

**Comment by lgvalle** [comment]
Major :+1:

On Thu, 30 Jun 2016, 17:54 Francesco Pontillo, <notifications@github.com>
wrote:

> On master? If this breaks the previous contract we should aim for a new
> major.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/novoda/sqlite-provider/pull/62#issuecomment-229719852>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAVoREqY2XNNbeAJ4P2W4e-G9aRM790Iks5qQ_SsgaJpZM4JCW_s>
> .
>

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

File: core/src/main/java/novoda/lib/sqliteprovider/provider/SQLiteContentProviderImpl.java [hunk 1]
```diff
@@ -96,14 +95,12 @@ private Uri insertSilently(Uri uri, ContentValues values) {
     protected int updateInTransaction(Uri uri, ContentValues values, String selection, String[] selectionArgs) {
         ContentValues insertValues = (values != null) ? new ContentValues(values) : new ContentValues();
```
Comment (takecare) [inline core/src/main/java/novoda/lib/sqliteprovider/provider/SQLiteContentProviderImpl.java]: i know this was already here but afaik we don't need to do this and can actually pass the `null` to `update()`

File: core/src/androidTest/java/novoda/lib/sqliteprovider/sqlite/InsertHelperTest.java [hunk 2]
```diff
@@ -143,7 +143,7 @@ private void onQueryOf(String tableName, CursorOperations cursorOperations) {
         }
     }
 
-    private static interface CursorOperations {
+    private interface CursorOperations {
```
Comment (takecare) [inline core/src/androidTest/java/novoda/lib/sqliteprovider/sqlite/InsertHelperTest.java]: 👍

File: core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java [hunk 3]
```diff
@@ -1,12 +1,22 @@
...
 
+import java.io.IOException;
+
+import novoda.lib.sqliteprovider.sqlite.ExtendedSQLiteOpenHelper;
+
 public class ContentProviderTest extends AndroidTestCase {
 
+    private static final String TABLE_NAME = "test";
+    private static final String COLUMN_PRIMARY_KEY = "column_primary_key";
+    private static final String COLUMN2 = "column2";
```
Comment (takecare) [inline core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java]: can we have a better name or is there a specific reason for this one?

Comment (lgvalle) [inline core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java]: No specific reason for this one but we couldn't find a better name because the data there is really not relevant for the test.
Suggestions welcome!
`A_COLUMN` 
`ANOTHER_COLUMN`
`A_COLUMN_HAS_NO_NAME`
?

File: core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java [hunk 4]
```diff
@@ -18,4 +28,46 @@ public void testMapping() throws Exception {
...
+
+        ContentValues values = new ContentValues(2);
+        values.put(COLUMN_PRIMARY_KEY, 1);
+        values.put(COLUMN2, 1);
+        helper.getWritableDatabase().insert(TABLE_NAME, null, values);
+    }
+
+    @Override
+    protected void tearDown() throws Exception {
+        super.tearDown();
```
Comment (blundell) [inline core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java]: nitpic: you don't actually have to call this, but what I was originally going to say was LIFO call this last line of hte method :)

File: core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java [hunk 5]
```diff
@@ -18,4 +28,46 @@ public void testMapping() throws Exception {
         assertTrue(cursor.getColumnIndexOrThrow("childs__id") > -1);
         assertTrue(cursor.getColumnIndexOrThrow("parents_name") > -1);
     }
+
+    public void test_GivenATableWithData_When_UpdatingNonexistentRow_Then_NumberOfAffectedRowsShouldBeZero() throws Exception {
```
Comment (blundell) [inline core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java]: 👍

**Comment by blundell** [comment]
👍

File: core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java (hunk 3 above)
Comment (takecare) [inline core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java]: so if it's not relevant you can name it `ANY_COLUMN` or `ANY_COLUMN_NAME`

Comment (joetimmins) [inline core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java]: +1 for `A_COLUMN_HAS_NO_NAME` 😂

Comment (frapontillo) [inline core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java]: Why didn't I think of that before? 👍 for `A_COLUMN_HAS_NO_NAME`

File: core/src/main/java/novoda/lib/sqliteprovider/provider/SQLiteContentProviderImpl.java (hunk 1 above)
Comment (eduardb) [inline core/src/main/java/novoda/lib/sqliteprovider/provider/SQLiteContentProviderImpl.java]: The following exception is thrown if I let null in there:
```
java.lang.IllegalArgumentException: Empty values
at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1542)
at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
at novoda.lib.sqliteprovider.provider.SQLiteContentProviderImpl.updateInTransaction(SQLiteContentProviderImpl.java:98)
```

Comment (takecare) [inline core/src/main/java/novoda/lib/sqliteprovider/provider/SQLiteContentProviderImpl.java]: 😱 weird. the docs state that `null` is a possible value but...
screen shot 2016-07-01 at 10 15 41
oh well...

File: core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java (hunk 3 above)
Comment (eduardb) [inline core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java]: Done in 93f6626. The column has a name 😛

File: core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java (hunk 4 above)
Comment (eduardb) [inline core/src/androidTest/java/novoda/lib/sqliteprovider/ContentProviderTest.java]: Done in 344a624

File: core/src/main/java/novoda/lib/sqliteprovider/provider/SQLiteContentProviderImpl.java (hunk 1 above)
Comment (eduardb) [inline core/src/main/java/novoda/lib/sqliteprovider/provider/SQLiteContentProviderImpl.java]: That means that the null guard is useless, as using `new ContentValues()` will also throw.

Comment (eduardb) [inline core/src/main/java/novoda/lib/sqliteprovider/provider/SQLiteContentProviderImpl.java]: Actually, I think that by "null is a possible value" they mean that a null value in the map is possible, not that the `values` itself can be null.

Comment (takecare) [inline core/src/main/java/novoda/lib/sqliteprovider/provider/SQLiteContentProviderImpl.java]: yeah, maybe it's that 👍  weird choice of words, still.
